FROM node:24-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN yarn install --frozen-lockfile

# Copy application code
COPY . .

# Expose Next.js port
EXPOSE 3000

# Run Next.js in development mode
CMD ["node", "node_modules/.bin/next", "dev"]

