import { Inter, Inria_Serif, Kaisei_Tokumin } from "next/font/google";

import type { Metadata } from "next";

import "./globals.css";

// Base font - Inter
const inter = Inter({
  variable: "--font-family-base",
  subsets: ["latin"],
  display: "swap",
});

// Hero font - Inria Serif
const inriaSerif = Inria_Serif({
  variable: "--font-family-hero",
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  display: "swap",
});

// Header font - Kaisei Tokumin
const kaiseiTokumin = Kaisei_Tokumin({
  variable: "--font-family-header",
  weight: ["400", "500", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.ReactElement {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${inriaSerif.variable} ${kaiseiTokumin.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
